services:
  complex-decision-ollama-llm:
    image: "ollama/ollama:0.5.12"
    container_name: complex-decision-ollama-llm
    ports:
      - "11434:11434"


  complex-decision-agent:
    build:
      context: .
    image: complex-decision:v2
    container_name: complex-decision-agent
    ports:
      - "8505:8501"
    depends_on:
      - complex-decision-ollama-llm
    env_file:
      - .env
