services:
  supply-chain-agent-frontend:
    build:
      context: frontend
    image: supply-chain-agent-frontend:v2
    container_name: supply-chain-agent-frontend
    ports:
      - "8506:8501"
    env_file:
      - .env
    depends_on:
      - supply-chain-agent-backend
  supply-chain-agent-backend:
    build:
      context: .
      dockerfile: ./Dockerfile-backend
    image: supply-chain-agent-backend:v2
    container_name: supply-chain-agent-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
